### ISSUE TITLE
Should this repo be deleted ?

### ISSUE THREAD

**Issue by jcfr** [InsightSoftwareConsortium/ITKCIDeployment#2]
It looks like it hasn't been updated in few years.

**Comment by jcfr** [comment]
Look like PR #1  is address this :+1:

**Comment by fbudin69500** [comment]
The images in https://github.com/InsightSoftwareConsortium/ITKDevelopmentEnvironment are designed to help developing ITK, not running continuous integration tests. I think what should be done is that the gcc-5.1 image should be moved from that repo to this one. After that is done, everything will be consistent and organize.
